import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { stripTypeScriptTypes } from 'node:module';
import { PGlite } from '@electric-sql/pglite';
import '../calendar-rules.js';
import '../package-billing.js';
const rules = globalThis.CalendarRules;
const source = fs.readFileSync(new URL('../script.js',import.meta.url),'utf8');
const read = (p) => fs.readFileSync(new URL(p,import.meta.url),'utf8');
function fn(name) {
  const start = source.indexOf(`function ${name}(`);
  assert.ok(start >= 0, name);
  return source.slice(start, source.indexOf('\n}',start)+2);
}
const marker = (active = true) => ({id:'holiday-2026-02-03',dateKey:'2026-02-03',time:'00:00',type:'global-holiday',holidayActive:active});
function logic(extra = {}) {
  const events = [marker()];
  const packages = [];
  const context = vm.createContext({CalendarRules:rules,PackageBilling:globalThis.PackageBilling,Intl,Date,console,
    loadAgendaEvents:() => events, loadClassPackages:() => packages,
    loadCheckins:() => [],loadBillingSettings:() => ({countHolidays:true}),loadFinancialHistory:()=>[],
    normalizeBillingDays:(d)=>d||[],normalizeBillingType:(v)=>v==='per_class'?'per_class':'fixed',
    normalizeBillingItems:(items)=>items||[],onlyDigits:(v)=>String(v).replace(/\D/g,''),
    getBillingStatusForStudent:()=> 'Pendente',getBillingDueDate:()=>null,
    getStudentCompletedLessonsForMonth:()=>0,...extra});
  for(const name of ['getGlobalHolidayKeys','isGlobalHoliday','getDateKey','parseBrazilianDate','getDefaultBillingMonthKey','getMonthBounds','getWeekdayName','countBillingLessonsForMonth','countBillingLessonsBetweenDates','parseCurrencyValue','getLegacyStudentBillingProjection','getStudentBillingProjection','parsePackageDays','generatePackageSchedule','isConsumedLesson','getLessonRecord','getPackageCheckins','getCompletedLessons','getPackageStatus']) vm.runInContext(fn(name),context);
  return {context,events,packages};
}
test('validade: início, término, encerramento e legado sem datas',()=>{
  const pack={total:8,startDate:'01/02/2026',endDate:'28/02/2026'};
  assert.equal(rules.packageState(pack,0,'2026-01-31'),'Ainda não começou');
  assert.equal(rules.packageState(pack,0,'2026-02-01'),'Ativo');
  assert.equal(rules.packageState(pack,0,'2026-03-01'),'Vencido');
  assert.equal(rules.packageState(pack,8,'2026-02-05'),'Encerrado');
  assert.equal(rules.packageState({total:8},0,'2026-02-01'),'Ativo');
  assert.equal(rules.schedulingError('2026-03-01',new Set(),pack),'Aula fora da validade do pacote.');
  assert.equal(rules.schedulingError('2026-01-31',new Set(),pack),'Aula fora da validade do pacote.');
  assert.equal(rules.dateKey('31/02/2026'),'');
});
test('8 previstas com 1 feriado: 7 cobradas; repetição e remoção restauram 8',()=>{
  const {context:c,events}=logic();
  const student={id:'s1',name:'Maria',billingType:'per_class',billingDays:[2,4],classValue:'R$ 60,00',value:'R$ 480,00'};
  let projection=c.getStudentBillingProjection(student,'2026-02');
  assert.equal(projection.predictedLessons,7); assert.equal(projection.totalValue,420);
  events.push(marker());
  assert.equal(c.getStudentBillingProjection(student,'2026-02').totalValue,420);
  events.splice(0,events.length,marker(false));
  projection=c.getStudentBillingProjection(student,'2026-02');
  assert.equal(projection.predictedLessons,8); assert.equal(projection.totalValue,480);
});
test('pacote automático: não usa valor congelado nem desconta feriado duas vezes',()=>{
  const {context:c,packages}=logic();
  packages.push({id:'p1',studentId:'s1',monthKey:'2026-02',autoGenerated:true,total:8,value:'R$ 480,00',startDate:'01/02/2026',endDate:'28/02/2026',days:'terça, quinta',time:'08:00'});
  const p=c.getStudentBillingProjection({id:'s1',billingType:'per_class',classValue:'R$ 60,00'},'2026-02');
  assert.equal(p.predictedLessons,7);assert.equal(p.totalValue,420);
  packages[0].value='R$ 700,00';
  assert.equal(c.getStudentBillingProjection({id:'s1',billingType:'fixed',value:'R$ 700,00'},'2026-02').totalValue,700);
});
test('mensalidade fixa, adicional por aula e saldo sem consumo no feriado',()=>{
  const {context:c,events}=logic();
  const student={billingType:'fixed',billingDays:[2,4],value:'R$ 700,00',billingItems:[{billingType:'per_class',billingDays:[2,4],classValue:'R$ 60,00'}]};
  assert.equal(c.getStudentBillingProjection(student,'2026-02').totalValue,1120);
  assert.equal(c.isConsumedLesson({dateKey:'2026-02-03',status:'aula-dada',consumed:true}),false);
  const record=c.getLessonRecord('p1','2026-02-03');
  assert.equal(record.status,'feriado'); assert.equal(record.generatedMakeup,false);
  const original={dateKey:'2026-02-03',status:'confirmada'};
  assert.equal(rules.overlay(original,rules.holidayKeys(events)).status,'feriado');
  assert.equal(original.status,'confirmada');
});
test('data local São Paulo na virada do dia; bloqueio global',()=>{
  assert.equal(rules.today(new Date('2026-02-04T02:30:00Z')),'2026-02-03');
  assert.match(rules.schedulingError('2026-02-03',new Set(['2026-02-03'])),/Feriado/);
});

test('remover feriado restaura consumo anterior sem alterar ou duplicar histórico',()=>{
  const records=[{id:'c1',packageId:'p1',dateKey:'2026-02-03',status:'aula-dada',consumed:true}];
  const {context:c,events}=logic({loadCheckins:()=>records});
  assert.equal(c.getCompletedLessons({id:'p1'}),0);
  events[0]=marker(false);
  assert.equal(c.getCompletedLessons({id:'p1'}),1);
  assert.equal(c.getLessonRecord('p1','2026-02-03').id,'c1');
  events[0]=marker();
  assert.equal(c.getCompletedLessons({id:'p1'}),0);
  assert.equal(records.length,1);assert.equal(records[0].status,'aula-dada');
});

test('Google: feriado confirmado com título Feriado e horário São Paulo; remoção restaura título',()=>{
  const c=vm.createContext({Date,Intl});
  vm.runInContext(stripTypeScriptTypes(read('../supabase/functions/_shared/calendar-sync.ts')).replace(/^import .*;\r?\n/gm,'').replace(/export /g,''),c);
  const event={id:'a1',dateKey:'2026-02-03',time:'08:00',studentName:'Maria',modality:'Personal',holiday:true};
  const payload=c.googlePayload(event);
  assert.equal(payload.summary,'Feriado');assert.equal(payload.status,'confirmed');
  assert.equal(payload.start.dateTime,'2026-02-03T11:00:00.000Z');
  assert.equal(payload.start.timeZone,'America/Sao_Paulo');
  assert.equal(c.googlePayload({...event,holiday:false}).summary,'Personal - Maria');
});

test('renderização: administrador e aluno mostram somente Feriado; pacote legado exibe campos não informados',()=>{
  const element=()=>({children:[],dataset:{},className:'',textContent:'',append(...items){this.children.push(...items);},appendChild(item){this.children.push(item);}});
  const grid=element();
  const {context:c}=logic({document:{createElement:element},adminAgendaGrid:grid,adminAgendaDate:{value:'03/02/2026'},adminAgendaView:{value:'day'},fillAgendaStudentSelects(){},fillAgendaCancelSelect(){},getAgendaRange:()=>({days:[new Date(2026,1,3)]}),getAgendaEventsForRange:()=>[{id:'a1',dateKey:'2026-02-03',time:'08:00',studentName:'Maria'}]});
  for(const name of ['renderAdminAgenda','createStudentLessonCard','createPackageSummaryCard']) vm.runInContext(fn(name),c);
  c.renderAdminAgenda();
  assert.equal(grid.children[0].children[1].textContent,'Feriado');
  assert.equal(grid.children[0].children.length,2);
  assert.equal(c.createStudentLessonCard({dateKey:'2026-02-03'},{id:'p1'}).textContent,'Feriado');
  const card=c.createPackageSummaryCard({id:'p1',name:'Antigo',total:8});
  const period=card.children[1].children.at(-1);
  assert.match(period.children[1].textContent,/Início não informado.*Término não informado/);
});

test('Google push: feriado idempotente e remoção restaura a aula no mesmo evento',async()=>{
  let link=null;const events=[marker()];const payloads=[];
  const db={from(table){const q={select(){return q;},eq(){return q;},async single(){return {data:{data:{agendaEvents:events}}};},async maybeSingle(){return {data:table==='lesson_cancellations'?null:link};},async upsert(row){if(table==='google_calendar_event_links')link={...row,id:'link'};return {};}};return q;}};
  const c=vm.createContext({Date,Intl,admin:()=>db,sha256:async(s)=>s,accessTokenFor:async()=>({accessToken:'test',connection:{calendar_id:'test'}}),googleFetch:async(token,path,request)=>{payloads.push({path,method:request.method,payload:JSON.parse(request.body)});return {id:'g1',etag:String(payloads.length)};}});
  vm.runInContext(stripTypeScriptTypes(read('../supabase/functions/_shared/calendar-sync.ts')).replace(/^import .*;\r?\n/gm,'').replace(/export /g,''),c);
  const lesson={id:'a1',dateKey:'2026-02-03',time:'08:00',studentName:'Maria',modality:'Personal',status:'confirmada'};
  await c.pushEvents('owner',[lesson]);
  assert.equal(payloads[0].payload.summary,'Feriado');
  assert.equal((await c.pushEvents('owner',[lesson]))[0].status,'ignored');
  assert.equal(payloads.length,1);
  events[0]=marker(false);await c.pushEvents('owner',[lesson]);
  assert.equal(payloads.length,2);assert.equal(payloads[1].method,'PATCH');
  assert.equal(payloads[1].payload.summary,'Personal - Maria');
});

test('webhook Google no feriado não gera cancelamento, saldo ou reposição',async()=>{
  const state={agendaEvents:[marker(),{id:'a1',dateKey:'2026-02-03',status:'confirmada'}],checkins:[],makeupCredits:[]};
  const db={from(table){const q={select(){return q;},eq(){return q;},async maybeSingle(){return {data:table==='lesson_cancellations'?null:table==='google_calendar_event_links'?{id:'link',app_event_id:'a1'}:null};}};return q;}};
  const c=vm.createContext({Date,Intl,admin:()=>db,updateAppState:async(_,mutate)=>mutate(state)});
  vm.runInContext(stripTypeScriptTypes(read('../supabase/functions/_shared/calendar-sync.ts')).replace(/^import .*;\r?\n/gm,'').replace(/export /g,''),c);
  const result=await c.applyGoogleEvent('owner',{id:'g1',status:'cancelled',start:{dateTime:'2026-02-03T11:00:00Z'},end:{dateTime:'2026-02-03T12:00:00Z'}});
  assert.equal(result.reason,'global-holiday');assert.equal(state.checkins.length,0);assert.equal(state.makeupCredits.length,0);assert.equal(state.agendaEvents[1].status,'confirmada');
});

test('migration preserva dados, protege feriados e bloqueia cancelamentos no banco',async()=>{
  const db=new PGlite();
  const owner='11111111-1111-4111-8111-111111111111',student='22222222-2222-4222-8222-222222222222';
  try {
    await db.exec(`create role anon;create role authenticated;create role service_role;
      create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
      insert into auth.users values('${owner}','jvictordesc99@gmail.com',now()),('${student}','student@example.com',now());
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      create table app_state(id text primary key,data jsonb,updated_at timestamptz);
      insert into app_state values('main','{"students":[{"id":"keep"}],"agendaEvents":[],"checkins":[]}',now());
      grant all on app_state to anon,authenticated,service_role;`);
    await db.exec(read('../supabase/migrations/202609010001_google_calendar_integration.sql').replace('create extension if not exists pgcrypto;',''));
    await db.exec(read('../supabase/migrations/202609300001_app_state_compare_and_swap.sql'));
    await db.exec(read('../supabase/migrations/202610010001_authenticated_cancellations.sql'));
    await db.exec(read('../supabase/migrations/202610070001_global_holidays.sql'));
    const as=async(id,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);};
    const update=async(events)=>db.query("update app_state set data=jsonb_set(data,'{agendaEvents}',$1) where id='main'",[JSON.stringify(events)]);
    await as(student);await assert.rejects(update([marker()]),/Somente o administrador/);
    await as('', 'anon');await assert.rejects(update([marker()]),/Somente o administrador/);
    await as(owner);await update([marker()]);await update([marker()]);
    assert.equal((await db.query("select data from app_state")).rows[0].data.students[0].id,'keep');
    await assert.rejects(update([marker(),{...marker(),id:'duplicate'}]),/duplicado/);
    await assert.rejects(update([marker(),{id:'new-booking',type:'package',source:'manual',dateKey:'2026-02-03'}]),/novos agendamentos/);
    await as(student);await assert.rejects(update([marker(false)]),/Somente o administrador/);
    await db.exec('reset role');
    await assert.rejects(db.exec("insert into lesson_cancellations(date_key) values('2026-02-03')"),/nao ha aula/);
    await as(owner);await update([marker(false)]);await update([marker(false)]);await update([marker()]);
    const state=(await db.query('select data from app_state')).rows[0].data;
    assert.equal(state.agendaEvents.length,1);assert.equal(state.checkins.length,0);
  } finally {await db.close();}
});

